drop schema if exists librarydb;
create schema librarydb;
use librarydb;

drop table if exists LIBRARY;
drop table if exists LIBRARIAN;
drop table if exists BOOKS;
drop table if exists CATEGORY;
drop table if exists SHELVES;
drop table if exists AUTHOR;
drop table if exists READERS;
drop table if exists ISSUEDATE;

##DO NOT RUN ALTER TABLES FOR FOREIGN KEYS UNTIL THE INSERT STATEMENTS HAVE BEEN RAN, THANKS :)
## ALTER STATEMENTS ARE AT END OF THIS FILE
## OTHER THAN THAT, EVERYTHING WORKS WONDERFUL

CREATE TABLE LIBRARY (
    BRANCHID 	INT		NOT NULL,
    MANAGERID 	INT,
    CITY 		VARCHAR(25),
    PRIMARY KEY (BRANCHID)
);

CREATE TABLE LIBRARIAN (
    EMPID 			INT				NOT NULL,
    NAME 			VARCHAR(100),
    BRANCHID 		INT,
    PRIMARY KEY (EMPID)
);

CREATE TABLE BOOKS (
    ISBN 			INT				NOT NULL,
    TITLE 			VARCHAR(100),
    GENREID 		INT,
    AUTHORNAME 		VARCHAR(100),
    SHELFNO 		INT,
    PRIMARY KEY (ISBN)
);

CREATE TABLE CATEGORY (
    GENREID 		INT				NOT NULL,
    GENRE 			VARCHAR(50),
    SHELFNO 		INT,
    PRIMARY KEY (GENREID)
);

CREATE TABLE SHELVES (
    SHELFNO 	INT		NOT NULL,
    FLOORNO 	INT,
    PRIMARY KEY (SHELFNO)
);

CREATE TABLE AUTHOR (
    NAME 		VARCHAR(100)		NOT NULL,
    PUBLISHER 	VARCHAR(150),
    PRIMARY KEY (NAME)
);

CREATE TABLE READERS (
    CUSTOMERID 		INT				NOT NULL,
    NAME 			VARCHAR(100),
    REGISTERDATE 	DATE,
    BOOKSISSUED 	INT,
    PRIMARY KEY (CUSTOMERID)
);

CREATE TABLE ISSUEDATE (
    ISSUEID 	INT				NOT NULL,
    DUEDATE 	DATE,
    BOOK 		VARCHAR(100),
    CUSTID		INT,
    ISBN		INT,
    CURRDATE    DATE,
    PRIMARY KEY (ISSUEID)	
);

## run after you insert data in insert tab

ALTER TABLE LIBRARY 
ADD CONSTRAINT fk_manager
FOREIGN KEY (MANAGERID) REFERENCES LIBRARIAN(EMPID);

ALTER TABLE  librarian 
ADD CONSTRAINT fk_branchID
FOREIGN KEY (BRANCHID) REFERENCES LIBRARY(BRANCHID);

ALTER TABLE  books 
ADD CONSTRAINT fk_books
FOREIGN KEY (GENREID) REFERENCES CATEGORY(GENREID),
ADD FOREIGN KEY (SHELFNO) REFERENCES SHELVES(SHELFNO);

ALTER TABLE  category 
ADD CONSTRAINT fk_category
FOREIGN KEY (SHELFNO) REFERENCES SHELVES(SHELFNO);

ALTER TABLE  readers 
ADD CONSTRAINT fk_readers
FOREIGN KEY (BOOKSISSUED) REFERENCES ISSUEDATE(ISSUEID);

ALTER TABLE  issuedate 
ADD CONSTRAINT fk_issue
FOREIGN KEY (CUSTID) REFERENCES READERS(CUSTOMERID),
ADD FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN);